### ISSUE TITLE
Difference between Meta-SGD and MAML

### ISSUE THREAD

**Issue by Mrxuefei** [foolyc/Meta-SGD#4]
Thank you for your paper and project！I find that the only difference between Meta-SGD and MAML in source code  is the update_lr is defined by tf.Variable(0.001, "updatelr") rather than  defined by meta_update_lr. Is that correct？

**Comment by foolyc** [comment]
@Mrxuefei **_It is not my paper.
 I jus test the performance_** of Meta-SGD and MAML, because it think the key point of Meta-SGD is interesting for me.

As you mentioned, the difference between Meta-SGD and MAML is that Meta-SGD make the inner learing rate(learning rate for single task) a learnable parameter, in other words, a adaptive learning rate for task updating.

As it increases the dimension of optimization(an important dimension which stands for the step size of updating), the space of the meta-learning system is much more powerful theoretically. **_But it can also introduces unstable issue in the learning process._**
